### ISSUE TITLE
ASPolicySample.java里面的testCreateAutoScalingPolicy()的launch time minutes error

### ISSUE THREAD

**Issue by caoyameng** [Huawei/openstack4j#10]
"{"error":{"code":"AS.3009","message":"The policy launch time minutes error."}}[\r][\n]"

这个跟新的版本是把 policy 改为RECURRENCE样例了，之前那个SCHEDULED样例为啥删了，我觉RECURRENCE、SCHEDULED、ALARM三种都放上吧，最后创完了再都删了就行

**Comment by caoyameng** [comment]
testOperateAutoScalingPolicy（）里面的assertTrue("INSERVICE".equals(policy.getPolicyStatus()）结果也不通过了

**Comment by IamFive** [comment]
额，写Scheduled没有难度吧，按照文档来应该很简单才对啊。

这个Sample项目是我们的测试在测试过程中，写的一些测试用例，放在这边，给你们那测试的时候作一个参考用的。实际发布给用户的时候，是不会包含这个sample项目的。

**Comment by IamFive** [comment]
那个测试用例 是要你们按照实际情况是修改的，那个policy的状态，在不同时间是不一样的。

**Comment by IamFive** [comment]
测试不是测那个测试用例。是要自己写代码，去测各个接口是否正常。

**Comment by caoyameng** [comment]
开会的时候我问张栋，他说端口的遍历场景不让我们自己写，让客户写。。。。。。

**Comment by IamFive** [comment]
汗，那你们是怎么测试的？跑一下我们写的Sample吗

**Comment by caoyameng** [comment]
policy的状态实际就是INSERVICE，get的信息也是对的，但加上assertTrue("INSERVICE".equals(policy.getPolicyStatus()执行结果就是FAIL，之前版本还是ok的。

**Comment by IamFive** [comment]
哦，看到了。。 那是个对象，不是 String 了。

改成 PolicyStatus.INSERVICE.equals ...

**Comment by caoyameng** [comment]
RECURRENCE样例里面没有starttime

**Comment by IamFive** [comment]
那个不是必填项。
