### ISSUE TITLE
AS创伸缩组， 加上availability_zones参数后说请求体错，帮看是格式不对吗

### ISSUE THREAD

**Issue by caoyameng** [Huawei/openstack4j#11]
日志："availability_zones" : [ "az1.dc1" ],[\r][\n]"

代码：
String availabilityZone = "az1.dc1";

.availabilityZones(Lists.newArrayList(availabilityZone))

**Comment by IamFive** [comment]
看这数据格式是没错的， 是不是没有这个 zone

**Comment by IamFive** [comment]
看了下文档。。是不是文档有问题。这个字段实际叫做 `available_zones` ? 你查下你手头的文档，我感觉我们这拿到的文档是错的。

**Comment by IamFive** [comment]
确认了 是叫做 available_zones

**Comment by caoyameng** [comment]
public ASAutoScalingGroupCreate.ASAutoScalingGroupCreateBuilder availabilityZones(List<String> availabilityZones) {
            this.availabilityZones = availabilityZones;
            return this;
        }
这个代码何如了么？我刚更新的代码，还是不行啊，名字没变啊

**Comment by IamFive** [comment]
发送的数据会变成

```
"available_zones " : [ "az1.dc1" ]
```

**Comment by caoyameng** [comment]
>> "  "availability_zones" : [ "az1.dc1" ],[\r][\n]"
加上这一项还是提示请求体错误

代码：
		IdResourceEntity network = new IdResourceEntity();
		network.setId("814fcf7b-2a78-4a6f-b68e-0646a6384bf1");

		IdResourceEntity securityGroup = new IdResourceEntity();
		securityGroup.setId("6c22a6c0-b5d2-4a84-ac56-51090dcc33be");

		String availabilityZone = "az1.dc1";

ASAutoScalingGroupCreate group = ASAutoScalingGroupCreate.builder().groupName("test-4-bill")
				.vpcId("eb83b023-3ffe-4ec7-b868-f2818fdc401f").networks(Lists.newArrayList(network))
				.configId("5d8cd9c2-5081-41e2-af81-710a6da0c531").securityGroups(Lists.newArrayList(securityGroup))
				.maxInstanceNumber(2).minInstanceNumber(1).desireInstanceNumber(1).coolDownTime(800)
				.lbListenerId("47c134f775834f9991fbe5e8c41b296b")
				.lbListenerId("e68450203ddf49be96232e9ec8951049")
				.availabilityZones(Lists.newArrayList(availabilityZone))
				//		.healthPeriodicAuditMethod("NOVA_AUDIT")
				.healthPeriodicAuditTime(15)
				//       .instanceTerminatePolicy("OLD_INSTANCE")
				.deletePublicip(true)
				.build();

**Comment by IamFive** [comment]
完整的代码贴给我看下

**Comment by caoyameng** [comment]
@Test
	public void testCreateAutoScalingGroup() {
		String groupId = createScalingGroup();
		logger.info(groupId);
	}


      private String createScalingGroup() {
	/*	IdResourceEntity network = new IdResourceEntity();
		network.setId("814fcf7b-2a78-4a6f-b68e-0646a6384bf1");

		IdResourceEntity securityGroup = new IdResourceEntity();
		securityGroup.setId("6c22a6c0-b5d2-4a84-ac56-51090dcc33be");

		ASAutoScalingGroupCreate group = ASAutoScalingGroupCreate.builder().groupName("test-4-bill")
				.vpcId("eb83b023-3ffe-4ec7-b868-f2818fdc401f").networks(Lists.newArrayList(network))
				.configId("5d8cd9c2-5081-41e2-af81-710a6da0c531").securityGroups(Lists.newArrayList(securityGroup))
				.maxInstanceNumber(2).minInstanceNumber(1).desireInstanceNumber(1).build();

		ScalingGroupCreate result = osclient.autoScaling().groups().create(group);
		Assert.assertNotNull(result.getGroupId());
		return result.getGroupId();*/

		//add by cym
		IdResourceEntity network = new IdResourceEntity();
		network.setId("814fcf7b-2a78-4a6f-b68e-0646a6384bf1");

		IdResourceEntity securityGroup = new IdResourceEntity();
		securityGroup.setId("6c22a6c0-b5d2-4a84-ac56-51090dcc33be");

		String availabilityZone = "az1.dc1";

		ASAutoScalingGroupCreate group = ASAutoScalingGroupCreate.builder().groupName("test-4-bill")
				.vpcId("eb83b023-3ffe-4ec7-b868-f2818fdc401f").networks(Lists.newArrayList(network))
				.configId("5d8cd9c2-5081-41e2-af81-710a6da0c531").securityGroups(Lists.newArrayList(securityGroup))
				.maxInstanceNumber(2).minInstanceNumber(1).desireInstanceNumber(1).coolDownTime(800)
				.lbListenerId("47c134f775834f9991fbe5e8c41b296b")
				.lbListenerId("e68450203ddf49be96232e9ec8951049")
				.availabilityZones(Lists.newArrayList(availabilityZone))
		//		.healthPeriodicAuditMethod("NOVA_AUDIT")
				.healthPeriodicAuditTime(15)
		//		.instanceTerminatePolicy("OLD_INSTANCE")
				.deletePublicip(true)
				.build();
		ScalingGroupCreate result = osclient.autoScaling().groups().create(group);
		Assert.assertNotNull(result.getGroupId());
		return result.getGroupId();
	}

**Comment by IamFive** [comment]
更新下
