### ISSUE TITLE
创伸缩组里面 healthPeriodicAuditMethod和instanceTerminatePolicy参数报错

### ISSUE THREAD

**Issue by caoyameng** [Huawei/openstack4j#13]
ASAutoScalingGroupCreate group = ASAutoScalingGroupCreate.builder().groupName("test-4-bill")
				.vpcId("eb83b023-3ffe-4ec7-b868-f2818fdc401f").networks(Lists.newArrayList(network))
				.configId("5d8cd9c2-5081-41e2-af81-710a6da0c531").securityGroups(Lists.newArrayList(securityGroup))
				.maxInstanceNumber(2).minInstanceNumber(1).desireInstanceNumber(1).coolDownTime(800)
				.lbListenerId("47c134f775834f9991fbe5e8c41b296b")
				.lbListenerId("e68450203ddf49be96232e9ec8951049")
				.availabilityZones(Lists.newArrayList(availabilityZone))
				.healthPeriodicAuditMethod(new HealthPeriodicAuditMethod("NOVA_AUDIT"))
				.healthPeriodicAuditTime(15)
			//	.instanceTerminatePolicy("OLD_INSTANCE")
				.deletePublicip(true)
				.build();

healthPeriodicAuditMethod提示找不到类

**Comment by biaocy** [comment]
是枚举，不是类；
一般这种固定的状态值不是String就是枚举

**Comment by IamFive** [comment]
HealthPeriodicAuditMethod.NOVA_AUDIT

**Comment by caoyameng** [comment]
HealthPeriodicAuditMethod 和InstanceTerminatePolicy都搜不到定义啊，

				.healthPeriodicAuditMethod(HealthPeriodicAuditMethod.NOVA_AUDIT)
		
				.instanceTerminatePolicy(InstanceTerminatePolicy.OLD_INSTANCE)

提示找不到符号；

**Comment by biaocy** [comment]
![qq 20170707220717](https://user-images.githubusercontent.com/7885426/27961245-aef8a7a4-6360-11e7-8d6e-27613d3a8f83.png)

**Comment by caoyameng** [comment]
你刚发的截图我看不到

**Comment by IamFive** [comment]
找不到符号，你要把包引入啊

**Comment by caoyameng** [comment]
import org.openstack4j.model.scaling.ScalingGroup.HealthPeriodicAuditMethod;
import org.openstack4j.model.scaling.ScalingGroup.InstanceTerminatePolicy;

**Comment by caoyameng** [comment]
引了

**Comment by IamFive** [comment]
找不到符号是哪个地方。

**Comment by caoyameng** [comment]
ASAutoScalingGroupCreate group = ASAutoScalingGroupCreate.builder().groupName("test-4-bill")
				.vpcId("eb83b023-3ffe-4ec7-b868-f2818fdc401f").networks(Lists.newArrayList(network))
				.configId("5d8cd9c2-5081-41e2-af81-710a6da0c531").securityGroups(Lists.newArrayList(securityGroup))
				.maxInstanceNumber(2).minInstanceNumber(1).desireInstanceNumber(1).coolDownTime(800)
				.lbListenerId("47c134f775834f9991fbe5e8c41b296b")
				.lbListenerId("e68450203ddf49be96232e9ec8951049")
				.availabilityZones(Lists.newArrayList(availabilityZone))
				.healthPeriodicAuditMethod(HealthPeriodicAuditMethod.NOVA_AUDIT)
				.healthPeriodicAuditTime(15)
			//	.instanceTerminatePolicy(InstanceTerminatePolicy.OLD_INSTANCE)
				.deletePublicip(true)
				.build();

**Comment by caoyameng** [comment]
@JsonProperty("health_periodic_audit_method")
	HealthPeriodicAuditMethod healthPeriodicAuditMethod;
  

这里的HealthPeriodicAuditMethod点不进去

**Comment by IamFive** [comment]
你代码没更新完整估计

**Comment by IamFive** [comment]
代码地址在 https://github.com/Huawei/openstack4j/blob/master/core/src/main/java/org/openstack4j/model/scaling/ScalingGroup.java
