### ISSUE TITLE
创建伸缩配置，怎么是调的ESC接口

### ISSUE THREAD

**Issue by caoyameng** [Huawei/openstack4j#14]

**Comment by caoyameng** [comment]
testListAutoScalingConfig()也是这问题，之前版本是好的

**Comment by IamFive** [comment]
日志别贴了。。里面都是敏感信息。

**Comment by IamFive** [comment]
是不是你的AbstractSample类里面配置的路径被人改掉了。你在内网测试，endpoint估计全部要重新覆盖。

![image](https://user-images.githubusercontent.com/1578702/27919086-57879cf4-62a3-11e7-9019-eb941c1711f8.png)

**Comment by caoyameng** [comment]
我不是只需要配我们AS服务的ENDPOING就可以了吗，其他服务的的我都注释掉了。更新代码之前这个样例是没有问题的。

**Comment by IamFive** [comment]
那个Sample里面会创建一个 `config` 出来，而创建 `config` 时候，需要的 keypair 参数要从 ECS 来。所以会访问 EVS 的 endpoint

**Comment by caoyameng** [comment]
String keyname = "AS_keypair";
		Keypair keypair = osclient.compute().keypairs().get(keyname);
		if (keypair == null) {
			osclient.compute().keypairs().create(keyname, null);
		}
这个keyPair不管环境中有没有对应的keyname总是NULL

**Comment by IamFive** [comment]
要换成你的环境中有的。。

**Comment by caoyameng** [comment]
是有的

**Comment by caoyameng** [comment]
帮帮忙，创配置的这个publicIp怎么写不对啊
	.publicIp(PublicIp.builder().eip(Eip.builder().ipType("TELCOM5").bandwidth(Bandwidth.PER).build()).build())

**Comment by IamFive** [comment]
```
		Bandwidth build = Bandwidth.builder().chargingMode(ChargingMode.TRAFFIC).shareType(ShareType.PER).size("100").build();
		Eip eip = Eip.builder().ipType(IpType.TELCOM5).bandwidth(build).build();
		PublicIp publicIp = PublicIp.builder().eip(eip).build();
```
大概是这样吧

**Comment by IamFive** [comment]
你有了 keypair-name 可以直接设置进去就可以了啊

**Comment by caoyameng** [comment]
密码登录方式提示不合法


20:07:08.959 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "  "scaling_configuration_name" : "test-config-name",[\r][\n]"
20:07:08.959 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "  "instance_config" : {[\r][\n]"
20:07:08.959 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "flavorRef" : "c2.medium",[\r][\n]"
20:07:08.959 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "imageRef" : "e215580f-73ad-429d-b6f2-5433947433b0",[\r][\n]"
20:07:08.959 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "disk" : [ {[\r][\n]"
20:07:08.960 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "      "size" : 40,[\r][\n]"
20:07:08.960 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "      "volume_type" : "SATA",[\r][\n]"
20:07:08.960 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "      "disk_type" : "SYS"[\r][\n]"
20:07:08.960 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    } ],[\r][\n]"
20:07:08.960 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "adminPass" : "123456",[\r][\n]"
20:07:08.960 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "public_ip" : {[\r][\n]"
20:07:08.960 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "      "eip" : {[\r][\n]"
20:07:08.960 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "        "ip_type" : "5_telcom",[\r][\n]"
20:07:08.960 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "        "bandwidth" : {[\r][\n]"
20:07:08.960 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "          "size" : "10",[\r][\n]"
20:07:08.960 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "          "share_type" : "PER",[\r][\n]"
20:07:08.961 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "          "charging_mode" : "traffic"[\r][\n]"
20:07:08.961 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "        }[\r][\n]"
20:07:08.961 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "      }[\r][\n]"
20:07:08.961 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    },[\r][\n]"
20:07:08.961 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "metadata" : {[\r][\n]"
20:07:08.961 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "      "key1" : "val1",[\r][\n]"
20:07:08.961 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "      "key2" : "val2"[\r][\n]"
20:07:08.961 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    },[\r][\n]"
20:07:08.961 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "user_data" : "fegrhtht"[\r][\n]"
20:07:08.961 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "  }[\r][\n]"
20:07:08.961 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "}"
20:07:10.458 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "HTTP/1.1 400 Bad Request[\r][\n]"
20:07:10.459 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "request_id: f844c957-dba8-4f47-8e0b-c5892314e5fb[\r][\n]"
20:07:10.459 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "X-Frame-Options: SAMEORIGIN[\r][\n]"
20:07:10.459 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "X-Content-Type-Options: nosniff[\r][\n]"
20:07:10.459 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "Cache-Control: no-cache, no-store, must-revalidate[\r][\n]"
20:07:10.459 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "Pragma: no-cache[\r][\n]"
20:07:10.459 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "Expires: Thu, 01 Jan 1970 00:00:00 GMT[\r][\n]"
20:07:10.459 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "X-XSS-Protection: 1; mode=block[\r][\n]"
20:07:10.459 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "Date: Fri, 07 Jul 2017 12:07:11 GMT[\r][\n]"
20:07:10.459 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "Accept-Ranges: bytes[\r][\n]"
20:07:10.459 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "Server: SecAs[\r][\n]"
20:07:10.459 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept[\r][\n]"
20:07:10.459 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "Content-Type: application/json[\r][\n]"
20:07:10.459 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "Transfer-Encoding: chunked[\r][\n]"
20:07:10.459 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "Connection: close[\r][\n]"
20:07:10.460 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "[\r][\n]"
20:07:10.460 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "60[\r][\n]"
20:07:10.460 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "{"error":{"code":"AS.1050","message":"The user login mode in the AS configuration is illegal."}}[\r][\n]"
20:07:10.460 [main] DEBUG org.apache.http.headers - http-outgoing-1 << HTTP/1.1 400 Bad Request
20:07:10.460 [main] DEBUG org.apache.http.headers - http-outgoing-1 << request_id: f844c957-dba8-4f47-8e0b-c5892314e5fb

**Comment by IamFive** [comment]
密码有问题吧。感觉你们服务端返回的错误信息 都不太友好

```
密码复杂度要求：
	长度为8-26位。
	密码只能包含大写字母、小写字母、数字和特殊字符（!@$%^-_=+[{}]:,./?）且至少包含四种字符中的三种。
	密码不能包含用户名或用户名的逆序。
	Windows系统密码不能包含用户名或用户名的逆序，不能包含用户名中超过两个连续字符的部分。

```

**Comment by caoyameng** [comment]
我按要求改了密码了，还是提示的是登录方式不对，用秘钥可以

**Comment by IamFive** [comment]
那我就不清楚了，是不是 Linux服务器不支持 密码登录，问下你们服务端的规则
