### ISSUE TITLE
AS:RecurrenceType.WEEKLY这种报Invalid period type

### ISSUE THREAD

**Issue by caoyameng** [Huawei/openstack4j#15]
代码：
	//RECURRENCE1 weekly add by cym                                                                                                                
	ScheduledPolicy scheduledPolicy00 = ScheduledPolicy.builder().launchTime("01:21")                                                              
			.recurrenceType(RecurrenceType.WEEKLY).startTime(getStartTime()).endTime(getEndTime()).recurrenceValue("1,2,3").build();               
	ScalingPolicyCreateUpdate policy00 = ASAutoScalingPolicyCreateUpdate.builder().policyName("SDK-policyName")                                    
			.groupId(groupId).policyType(ScalingPolicyType.RECURRENCE).scheduledPolicy(scheduledPolicy00).coolDownTime(800)                        
			.scalingPolicyAction(ScalingPolicyAction.builder().operation(Operation.ADD).build())                                                   
			.build();                                                                                                                              
	ScalingPolicyCreateUpdate create00 = osclient.autoScaling().policies().create(policy00);                                                       
	assertTrue(create00 != null && !Strings.isNullOrEmpty(create00.getPolicyId()));       

日志：
   14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "Accept-Encoding: gzip,deflate[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "{[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "  "scaling_policy_name" : "SDK-policyName",[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "  "scaling_group_id" : "ab65a98b-dfcf-41a7-8c6d-3df5470f6de1",[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "  "scaling_policy_type" : "RECURRENCE",[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "  "scheduled_policy" : {[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "launch_time" : "01:21",[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "recurrence_type" : "WeekLy",[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "recurrence_value" : "1,2,3",[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "start_time" : "2017-07-07T06:58Z",[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "end_time" : "2017-07-28T02:58Z"[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "  },[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "  "scaling_policy_action" : {[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "operation" : "ADD"[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "  },[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "  "cool_down_time" : 800[\r][\n]"
14:58:36.425 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "}"
14:58:36.559 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "HTTP/1.1 400 Bad Request[\r][\n]"                                                      
                            
14:58:36.560 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "{"error":{"code":"AS.3004","message":"Invalid period type."}}[\r][\n]"

**Comment by IamFive** [comment]
稍等

**Comment by IamFive** [comment]
`WeekLy` 的拼写错了。。

**Comment by caoyameng** [comment]
我还是没看出来哪错了

**Comment by IamFive** [comment]
代码里面错了，是 `Weekly` 不是 `WeekLy`

**Comment by IamFive** [comment]
更新下
