### ISSUE TITLE
【DNS】getRecordset()缺少对不存在的zoneid和recordset id做校验，对不存在的zoneid和recordset id操作，仍可执行成功，未报错

### ISSUE THREAD

**Issue by dnstester** [Huawei/openstack4j#17]

**Comment by IamFive** [comment]
返回什么东西是根据服务端来的。服务端假如返回 400 以上的状态码，那么就会抛异常，如果服务端返回正常的状态吗 200-300，那么就是正常的请求。

**Comment by IamFive** [comment]
我现在测试不了，德电非常慢。。连接timeout，等可以连接的时候，我看下服务端返回什么数据

**Comment by IamFive** [comment]
我在德电环境测试的。不管是zone-id不存在，还是recordset-id不存在，在get的时候，都会抛出异常

ClientResponseException{message=[DNS.0309] Invalid record set ID., status=400, status-code=BAD_REQUEST}
