### ISSUE TITLE
createScalingConfig() 在德电测，eip报错

### ISSUE THREAD

**Issue by caoyameng** [Huawei/openstack4j#21]
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "{[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "  "scaling_configuration_name" : "test-config-name",[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "  "instance_config" : {[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "flavorRef" : "c2.medium",[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "imageRef" : "1688aaf4-feb1-43f5-a195-9942adaca70e",[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "disk" : [ {[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "      "size" : 40,[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "      "volume_type" : "SATA",[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "      "disk_type" : "SYS"[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    } ],[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "key_name" : "AS_keypair",[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "public_ip" : {[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "      "eip" : {[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "        "ip_type" : "5_telcom",[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "        "bandwidth" : {[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "          "size" : "100",[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "          "share_type" : "PER",[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "          "charging_mode" : "traffic"[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "        }[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "      }[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    },[\r][\n]"
19:03:26.384 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "metadata" : {[\r][\n]"
19:03:26.385 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "      "key1" : "val1",[\r][\n]"
19:03:26.385 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "      "key2" : "val2"[\r][\n]"
19:03:26.385 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    },[\r][\n]"
19:03:26.385 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "    "user_data" : "fegrhtht"[\r][\n]"
19:03:26.385 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "  }[\r][\n]"
19:03:26.385 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "}"
19:03:26.464 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "HTTP/1.1 400 Bad Request[\r][\n]"
19:03:26.464 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "request_id: 6132131e-fe08-4594-af50-fc8152a603af[\r][\n]"

19:03:26.464 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "{"error":{"code":"AS.1043","message":"the eip type of scaling config is invalid."}}[\r][\n]"

ClientResponseException{message=[AS.1043] the eip type of scaling config is invalid.
, status=400, status-code=BAD_REQUEST}

**Comment by biaocy** [comment]
提示是eip type无效，试了下 #20 返回的`5_bgp`类型，是可以通过的，麻烦确认下AS文档的ip_type的确切取值范围
