### ISSUE TITLE
使用Connection类来进行创建,运行失败

### ISSUE THREAD

**Issue by caoyameng** [Huawei/openstack4j#23]
安装方式：
pip install -r requirements.txt
python setup.py install
安装成功
开发环境eclipse + pydev 
在python-openstacksdk\openstack目录下面新建一个connect_bak.py
改文件拷贝以下代码并修改相关信息：
import os

from openstack import connection

os.environ.setdefault(
    'OS_CLOUD_EYE_ENDPOINT_OVERRIDE',
    'https://ces.eu-de.otc.t-systems.com/V1.0/%(project_id)s'
)

conn = connection.Connection(auth_url="https://iam.eu-de.otc.t-systems.com/v3",
                             project_id="d4f2557d248e4860829f5fef030b209c",
                             user_domain_id="bb42e2cd2b784ac4bdc350fb660a2bdb",
                             username="*********",
                             password="*********")

直接运行connect_bak.py文件

error log:
No property tester contributes a property org.eclipse.wst.jsdt.chromium.debug.core.isFile to type class org.python.pydev.navigator.elements.PythonFile

**Comment by caoyameng** [comment]
我ISSUSE好像提错位置了

**Comment by IamFive** [comment]
从日志来看。。好像是IDE的问题。跟代码没关系。

你可以在任意位置创建一个文件(比如 sdk.py)，然后 直接 python sdk.py 就可以了

```
import os

from openstack import connection

os.environ.setdefault(
    'OS_CLOUD_EYE_ENDPOINT_OVERRIDE',
    'https://ces.eu-de.otc.t-systems.com/V1.0/%(project_id)s'
)

conn = connection.Connection(auth_url="https://iam.eu-de.otc.t-systems.com/v3",
                             project_id="d4f2557d248e4860829f5fef030b209c",
                             user_domain_id="bb42e2cd2b784ac4bdc350fb660a2bdb",
                             username="******",
                             password="******")

zones = conn.dns.zones(limit=20)
for zone in zones:
    print zone
```

**Comment by IamFive** [comment]
issue我关了哈，有问题，提到 https://github.com/Huawei/python-openstacksdk

**Comment by caoyameng** [comment]
我换成pycharm了，运行出来没日志，醉了
随便运行哪个文件都没日志，就只有下面的：
C:\Python27\python.exe C:/Python27/Lib/site-packages/python-openstacksdk/openstack/auto_scaling/auto_scaling_service.py

Process finished with exit code 0

**Comment by IamFive** [comment]
python的也是你测试吗，本来测这些都要懂开发来测的。。

你运行的那个文件是个测试类文件，当然跑不了了。。他根本就没有执行入口。
你可以右键那个文件，然后选择 run as nosetest
![image](https://user-images.githubusercontent.com/1578702/28118645-71f66c1e-6744-11e7-8886-55e576cb6d86.png)

**Comment by IamFive** [comment]
如果要执行整个目录下的测试用例：


![image](https://user-images.githubusercontent.com/1578702/28118692-a609e94a-6744-11e7-8153-180faa91e61e.png)

**Comment by IamFive** [comment]
这个测试用例官方是用 testng 管理的，但是是兼容 nosetest的，本地可以直接用nosetest跑

**Comment by IamFive** [comment]
假如是要执行一个python文件。

![image](https://user-images.githubusercontent.com/1578702/28118755-edb32d38-6744-11e7-885f-6b86693ff220.png)

**Comment by caoyameng** [comment]
截图看不见，pycharm不能直接运行啊，那我还得装一下nosetest是不？

**Comment by caoyameng** [comment]
我用nosetest运行了，报错 Cloud devstack-admin was not found

**Comment by caoyameng** [comment]
1. 用nosetest命令运行单元测试的文件夹
C:\Python27\Lib\site-packages\python-openstacksdk\openstack\tests\unit\auto_scaling\v1
提示no module name mock

2.我用nosetest执行功能测试
C:\Python27\Lib\site-packages\python-openstacksdk\openstack\tests\functional\auto_scaling\test1
test1里面放了内容如下的test_sdk.by文件，报错the plugin password cannot be found;














import os

from openstack import connection

os.environ.setdefault(
    'OS_CLOUD_EYE_ENDPOINT_OVERRIDE',
    'https://ces.eu-de.otc.t-systems.com/V1.0/%(project_id)s'
)

conn = connection.Connection(auth_url="https://iam.eu-de.otc.t-systems.com/v3",
                             project_id="d4f2557d248e4860829f5fef030b209c",
                             user_domain_id="bb42e2cd2b784ac4bdc350fb660a2bdb",
                             username="*********",
                             password="*********")

**Comment by IamFive** [comment]
1. 需要先执行 pip install -r test-requirements.txt 安装测试依赖。

**Comment by caoyameng** [comment]
pip install -r test-requirements.txt执行了，全成功了

**Comment by caoyameng** [comment]
keystoneauth1.exceptions.auth_plugins.NoMatchingPlugin: The plugin password could not be found

**Comment by IamFive** [comment]
看第二点

**Comment by caoyameng** [comment]
求助：重新安装一下，在C:\Python27\Lib\site-packages\python-openstacksdk路径下
执行pip install -r requirements.txt，没有报错
接着执行python setup.py install，报错：decoding unicode is not supported

**Comment by IamFive** [comment]
= = 你在另外那个项目开个issue吧。。这个是java的啊。

哪个文件报错了。这个正常是因为项目里面有中文。
