### ISSUE TITLE
[DNS服务]匹配提示字段，应该用哪个函数？

### ISSUE THREAD

**Issue by dnstester** [Huawei/openstack4j#24]
例如：
	@Test
	public void delRecordset() {
		Recordset recordset = osclient.dns().recordsets().delete(ZONE_ID, "2c9eb1555d10b467015d309a2c6e0ff8");
		logger.info("Delete recordset: {}", recordset);
//		Assert.assertEquals(recordset.getStatus(),"PENDING_DELETE");
		Assert.assertEquals(recordset.getStatus(), org.openstack4j.model.dns.v2.Status.PENDING_DELETE);
	}

其中，报错“This record set does not exist”，如何匹配此字段？

**Comment by IamFive** [comment]
recordset 你自己创建出来，然后不就有ID了吗

**Comment by dnstester** [comment]
我的意思是，想对zoneid无效的测试点做判断，判断有这个字段，则此用例成功

**Comment by IamFive** [comment]
@dnstester  没理解你意思

**Comment by dnstester** [comment]
我的意思是，添加异常场景测试，当zone id不存在时，报错“This record set does not exist”，我进行字段匹配，若匹配成功，则此用例pass

**Comment by IamFive** [comment]
哦 这样，你直接 try catch 就可以了，在catcha 里面判断 Exception 的message

**Comment by IamFive** [comment]
大概是这样，

try {
Recordset recordset = osclient.dns().recordsets().delete(ZONE_ID, "2c9eb1555d10b467015d309a2c6e0ff8");
} catch(Exception e) {
Assert.assertEqual(e.getMessage(), "xxxx");
}
