### ISSUE TITLE
【DNS服务】未对EIP做无效检验

### ISSUE THREAD

**Issue by dnstester** [Huawei/openstack4j#26]
/*add by yuananna
des:PTR invaild*/

	@Test
	public void getPTR1() {
		try {
			DesignatePTR ptr = osclient.dns().ptrs().get(REGION,
					"XX50a0fe-9fa3-41eb-beac-d889ee3c3d88");
			logger.info("PTR: {}", ptr);
		}catch (Exception e) {
			Assert.assertEquals(e.getMessage(), "[DNS.0012] An error occurred when the VPC service is called.{\"code\":\"0000010002\",\"message\":\"{\\\"NeutronError\\\":{\\\"message\\\":\\\"Invalid floatingip_id.\\\",\\\"type\\\":\\\"InvalidInput\\\",\\\"detail\\\":\\\"\\\"}}\"}");
		}
	}

创建PTR中，当EIP为无效时，预期提示"[DNS.0012] An error occurred when the VPC service is called.{\"code\":\"0000010002\",\"message\":\"{\\\"NeutronError\\\":{\\\"message\\\":\\\"Invalid floatingip_id.\\\",\\\"type\\\":\\\"InvalidInput\\\",\\\"detail\\\":\\\"\\\"}}\"}"); 实际返回：
[main] INFO  o.o.sample.dns.v2.DNSSample - PTR: null

【建议】
对EIP进行有效性校验

**Comment by IamFive** [comment]
额，你把日志打开，确认下服务端返回的是什么。错误信息我们都是根据服务端返回输出的。

**Comment by IamFive** [comment]
这个问题是这样的。服务端返回的是 404，对于 404 的返回值，默认是当作null输出处理（其实很合理）。
如果确定要改成异常抛出，我们这边做个调整就好了。

**Comment by dnstester** [comment]
建议加上吧

**Comment by IamFive** [comment]
你确认下。。这个改同时还有许许多多其他的。是要一起改，还是就这个改。

**Comment by IamFive** [comment]
我说的是 404 的情况哈，你那个返回码 是 404 吗？

**Comment by IamFive** [comment]
404 返回null对用户来说友好很多。你想一下使用场景就知道了。

1. 假如要抛异常，每次 get 一个资源都要 自行添加 try catch 。。。
```
try {
osclient.service().resources().get("not-exists-id");
} catch(Exception e) {

}
```

2. 假如返回null
```
Resource resouce = osclient.service().resources().get("not-exists-id");
if (resource != null) {
xxxx
}
```

**Comment by IamFive** [comment]
长时间无回复，暂关闭。
