### ISSUE TITLE
EVS没有注册服务是吧

### ISSUE THREAD

**Issue by tunsuy** [Huawei/openstack4j#28]
比如我要获取一个卷Volume，endpoint没法配置

**Comment by IamFive** [comment]
哪些服务需要注册，要看你使用的环境。根据实际情况来设置。有些环境的iam服务里已经注册了部分服务，就不需要设置。那如果环境没注册，就需要自己手动注册。

**Comment by IamFive** [comment]
注册方法都是一样的。看文档里面怎么写的。

**Comment by tunsuy** [comment]
文档中没有写EVS对应的ServiceType，我从哪里可以拿到

**Comment by IamFive** [comment]
就是对应的服务名称，java里面有一个enum对应，在 `org.openstack4j.api.types.ServiceType` 。

evs 的服务名称应该就是 volume，你也可以直接 设置.
