### ISSUE TITLE
下载最新代码，编译失败

### ISSUE THREAD

**Issue by caoyameng** [Huawei/openstack4j#29]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
3:compile (default-compile) on project openstack4j-sample: Compilation failure:
Compilation failure:
[ERROR] /D:/workspace_sdk/openstack4j-master/sample/src/main/java/org/openstack4
j/sample/Run.java:[5,63] 程序包org.openstack4j.openstack.message.notification.co
nstant不存在
[ERROR] /D:/workspace_sdk/openstack4j-master/sample/src/main/java/org/openstack4
j/sample/Run.java:[6,61] 程序包org.openstack4j.openstack.message.notification.do
main不存在
[ERROR] /D:/workspace_sdk/openstack4j-master/sample/src/main/java/org/openstack4
j/sample/Run.java:[7,62] 程序包org.openstack4j.openstack.message.notification.op
tions不存在
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :openstack4j-sample

**Comment by IamFive** [comment]
b不小心提交上去了。。删除掉了
