### ISSUE TITLE
查询集群报错

### ISSUE THREAD

**Issue by swx424265** [Huawei/openstack4j#32]
10:43:20.887 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://192.168.53.150:31943][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
10:43:21.402 [main] DEBUG org.openstack4j.core.transport.internal.HttpExecutor - Executing Request: https://192.168.77.211:20002/api-gateway/v1.1/d85144a2ccb04f048f60483d0f58ead1 -> /cluster_infos/445804e4-392c-414c-949d-ab35d4218bb6
10:43:21.402 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: best-match
10:43:21.402 [main] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
10:43:21.402 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://192.168.77.211:20002][total kept alive: 1; route allocated: 0 of 2; total allocated: 1 of 20]
10:43:21.402 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection leased: [id: 1][route: {s}->https://192.168.77.211:20002][total kept alive: 1; route allocated: 1 of 2; total allocated: 2 of 20]
10:43:21.402 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Opening connection {s}->https://192.168.77.211:20002
10:43:21.402 [main] DEBUG org.apache.http.impl.conn.HttpClientConnectionOperator - Connecting to /192.168.77.211:20002
10:43:21.528 [main] DEBUG org.apache.http.impl.conn.HttpClientConnectionOperator - Connection established 170.2.0.145:52204<->192.168.77.211:20002
10:43:21.528 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Executing request GET /api-gateway/v1.1/d85144a2ccb04f048f60483d0f58ead1/cluster_infos/445804e4-392c-414c-949d-ab35d4218bb6 HTTP/1.1
10:43:21.528 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
10:43:21.528 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
10:43:21.528 [main] DEBUG org.apache.http.headers - http-outgoing-1 >> GET /api-gateway/v1.1/d85144a2ccb04f048f60483d0f58ead1/cluster_infos/445804e4-392c-414c-949d-ab35d4218bb6 HTTP/1.1
10:43:21.528 [main] DEBUG org.apache.http.headers - http-outgoing-1 >> Accept: application/json; charset=utf-8
10:43:21.528 [main] DEBUG org.apache.http.headers - http-outgoing-1 >> X-Auth-Token: MIIDqwYJKoZIhvcNAQcCoIIDnDCCA5gCAQExDTALBglghkgBZQMEAgEwggH5BgkqhkiG9w0BBwGgggHqBIIB5nsidG9rZW4iOnsiaXNzdWVkX2F0IjoiMjAxNy0wNy0yNlQwMjo0MToxNC4wNDYwMDBaIiwiZXhwaXJlc19hdCI6IjIwMTctMDctMjdUMDI6NDE6MTQuMDQ2MDAwWiIsIm1ldGhvZHMiOlsicGFzc3dvcmQiXSwicHJvamVjdCI6eyJuYW1lIjoiZXUtZGUiLCJpZCI6ImQ4NTE0NGEyY2NiMDRmMDQ4ZjYwNDgzZDBmNThlYWQxIiwiZG9tYWluIjp7Im5hbWUiOiJtcnN3YW54aW5naHVhIiwiaWQiOiIwODdjN2I0NDA1OWI0MmFkYTRmNTY1OWE4MTZhZjUwNCJ9fSwidXNlciI6eyJkb21haW4iOnsibmFtZSI6Im1yc3dhbnhpbmdodWEiLCJpZCI6IjA4N2M3YjQ0MDU5YjQyYWRhNGY1NjU5YTgxNmFmNTA0In0sImlkIjoiZTg4MTZkOTExMjNiNDM2OThlMjA2YmFiODc2Njk0M2QiLCJuYW1lIjoiYXV0b3Rlc3RvciJ9LCJjYXRhbG9nIjpbXSwicm9sZXMiOlt7Im5hbWUiOiJ0ZV9hZG1pbiIsImlkIjoiZTE5YzQ4NjAxMWUwNDY0NDg5YTdlYzk1NjJjNWI1MjIifV19fTGCAYUwggGBAgEBMFwwVzELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVuc2V0MQ4wDAYDVQQHDAVVbnNldDEOMAwGA1UECgwFVW5zZXQxGDAWBgNVBAMMD3d3dy5leGFtcGxlLmNvbQIBATALBglghkgBZQMEAgEwDQYJKoZIhvcNAQEBBQAEggEAS8hEgyNkurT9feSWyplILzl2GcbMde-fxLTEwM8BR+bF25HO+wO-wxaWsg2xwCVZHrOSvlq2NoRlqNWJn8YzgAHDV15++-NtXxJ2NBjLwmbpvXBW-31ap9RhLJ9PChIy+vSr7bvJJrbr4NHVjNgaFKBM80CnDu5gnu93yrybPw+5nHl6ZCJsFN5xwTPxTWdxXLhj7BpO1oOAfsofNix8wJkxU4Y8fVe5KYSDvBX3XygfqF1rTQkN7SuCRdNEkJGCLMPGvzZXxzgDbL+YdrQw4Y3QVruOOovJyc3Av5bW-dSW9yfz66pC16hpQ64ksr24DP3K3DYPUr0djG9xmprjOA==
10:43:21.528 [main] DEBUG org.apache.http.headers - http-outgoing-1 >> User-Agent: OpenStack4j / OpenStack Client
10:43:21.528 [main] DEBUG org.apache.http.headers - http-outgoing-1 >> Content-Type: application/json;charset=utf-8
10:43:21.528 [main] DEBUG org.apache.http.headers - http-outgoing-1 >> Host: 192.168.77.211:20002
10:43:21.528 [main] DEBUG org.apache.http.headers - http-outgoing-1 >> Connection: Keep-Alive
10:43:21.528 [main] DEBUG org.apache.http.headers - http-outgoing-1 >> Accept-Encoding: gzip,deflate
10:43:21.528 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "GET /api-gateway/v1.1/d85144a2ccb04f048f60483d0f58ead1/cluster_infos/445804e4-392c-414c-949d-ab35d4218bb6 HTTP/1.1[\r][\n]"
10:43:21.528 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "Accept: application/json; charset=utf-8[\r][\n]"
10:43:21.528 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "X-Auth-Token: MIIDqwYJKoZIhvcNAQcCoIIDnDCCA5gCAQExDTALBglghkgBZQMEAgEwggH5BgkqhkiG9w0BBwGgggHqBIIB5nsidG9rZW4iOnsiaXNzdWVkX2F0IjoiMjAxNy0wNy0yNlQwMjo0MToxNC4wNDYwMDBaIiwiZXhwaXJlc19hdCI6IjIwMTctMDctMjdUMDI6NDE6MTQuMDQ2MDAwWiIsIm1ldGhvZHMiOlsicGFzc3dvcmQiXSwicHJvamVjdCI6eyJuYW1lIjoiZXUtZGUiLCJpZCI6ImQ4NTE0NGEyY2NiMDRmMDQ4ZjYwNDgzZDBmNThlYWQxIiwiZG9tYWluIjp7Im5hbWUiOiJtcnN3YW54aW5naHVhIiwiaWQiOiIwODdjN2I0NDA1OWI0MmFkYTRmNTY1OWE4MTZhZjUwNCJ9fSwidXNlciI6eyJkb21haW4iOnsibmFtZSI6Im1yc3dhbnhpbmdodWEiLCJpZCI6IjA4N2M3YjQ0MDU5YjQyYWRhNGY1NjU5YTgxNmFmNTA0In0sImlkIjoiZTg4MTZkOTExMjNiNDM2OThlMjA2YmFiODc2Njk0M2QiLCJuYW1lIjoiYXV0b3Rlc3RvciJ9LCJjYXRhbG9nIjpbXSwicm9sZXMiOlt7Im5hbWUiOiJ0ZV9hZG1pbiIsImlkIjoiZTE5YzQ4NjAxMWUwNDY0NDg5YTdlYzk1NjJjNWI1MjIifV19fTGCAYUwggGBAgEBMFwwVzELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVuc2V0MQ4wDAYDVQQHDAVVbnNldDEOMAwGA1UECgwFVW5zZXQxGDAWBgNVBAMMD3d3dy5leGFtcGxlLmNvbQIBATALBglghkgBZQMEAgEwDQYJKoZIhvcNAQEBBQAEggEAS8hEgyNkurT9feSWyplILzl2GcbMde-fxLTEwM8BR+bF25HO+wO-wxaWsg2xwCVZHrOSvlq2NoRlqNWJn8YzgAHDV15++-NtXxJ2NBjLwmbpvXBW-31ap9RhLJ9PChIy+vSr7bvJJrbr4NHVjNgaFKBM80CnDu5gnu93yrybPw+5nHl6ZCJsFN5xwTPxTWdxXLhj7BpO1oOAfsofNix8wJkxU4Y8fVe5KYSDvBX3XygfqF1rTQkN7SuCRdNEkJGCLMPGvzZXxzgDbL+YdrQw4Y3QVruOOovJyc3Av5bW-dSW9yfz66pC16hpQ64ksr24DP3K3DYPUr0djG9xmprjOA==[\r][\n]"
10:43:21.529 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "User-Agent: OpenStack4j / OpenStack Client[\r][\n]"
10:43:21.529 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "Content-Type: application/json;charset=utf-8[\r][\n]"
10:43:21.529 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "Host: 192.168.77.211:20002[\r][\n]"
10:43:21.529 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
10:43:21.529 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "Accept-Encoding: gzip,deflate[\r][\n]"
10:43:21.529 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "[\r][\n]"
10:43:21.560 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "HTTP/1.1 404 Not Found[\r][\n]"
10:43:21.560 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "Content-Type: application/json;charset=utf-8[\r][\n]"
10:43:21.560 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "Transfer-Encoding: chunked[\r][\n]"
10:43:21.560 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "Date: Wed, 26 Jul 2017 02:41:48 GMT[\r][\n]"
10:43:21.560 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "Server: SecAs[\r][\n]"
10:43:21.560 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "[\r][\n]"
10:43:21.560 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "41[\r][\n]"
10:43:21.560 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "{"errorCode":"12000010","message":"URL does not exist!","url":""}[\r][\n]"
10:43:21.560 [main] DEBUG org.apache.http.headers - http-outgoing-1 << HTTP/1.1 404 Not Found
10:43:21.560 [main] DEBUG org.apache.http.headers - http-outgoing-1 << Content-Type: application/json;charset=utf-8
10:43:21.560 [main] DEBUG org.apache.http.headers - http-outgoing-1 << Transfer-Encoding: chunked
10:43:21.560 [main] DEBUG org.apache.http.headers - http-outgoing-1 << Date: Wed, 26 Jul 2017 02:41:48 GMT
10:43:21.560 [main] DEBUG org.apache.http.headers - http-outgoing-1 << Server: SecAs
10:43:21.560 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
10:43:21.560 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-1: Shutdown connection
10:43:21.560 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection discarded
10:43:21.560 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-1: Close connection
10:43:21.560 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 1][route: {s}->https://192.168.77.211:20002][total kept alive: 1; route allocated: 0 of 2; total allocated: 1 of 20]
200<_>null

**Comment by IamFive** [comment]
有敏感信息，已经帮你移除了。

这个是你本地环境的问题吧，在德电上测试通过。

**Comment by IamFive** [comment]
返回 404 是不是 ID 错了。

**Comment by swx424265** [comment]
确认了，这个集群是我手动创建的，集群id是直接粘过来的

**Comment by IamFive** [comment]
![image](https://user-images.githubusercontent.com/1578702/28602551-48349a10-71f1-11e7-9993-317a3eee222b.png)

我本地de的测试用例。你问下你环境的MRS部署。

**Comment by swx424265** [comment]
看不到图片……

**Comment by IamFive** [comment]
总之就是 德电环境没问题。。。

**Comment by swx424265** [comment]
{"errorCode":"12000010","message":"URL does not exist!","url":""}这个错误码啥意思，文档没查到

**Comment by IamFive** [comment]
不清楚。。看意思是那个链接无法访问。我觉得不是部署问题，就是网关那边转发的问题。

**Comment by IamFive** [comment]
hello, 这个问题在德电验证过了吗？
