### ISSUE TITLE
【VBS】删除备份接口异常

### ISSUE THREAD

**Issue by tunsuy** [Huawei/openstack4j#35]
接口：osclient.blockStorage().backups().delete(backupId)

返回这样的信息：
```java
"message":"Api does not exist","request_id":"45fffda9-1aa8-4475-ad8c-6da2ca3f7652"
```

**Comment by IamFive** [comment]
完整的 http 请求日志。

`org.openstack4j.sample.vbs.VolumeBackupSample`  有完整的功能测试用例。可以直接在德电上运行，运行时间会较长（需要等待备份完成）。

**Comment by tunsuy** [comment]
恩，好的，我是在HEC类生产上测试，我去德电试下

**Comment by IamFive** [comment]
长时间无回复，暂关闭。
