### ISSUE TITLE
创建集群时传参错误

### ISSUE THREAD

**Issue by swx424265** [Huawei/openstack4j#40]
@Getter
@ToString
@Builder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
public class SaharaComponent {

	@JsonProperty("componentId")
	String id;
	@JsonProperty("componentName")
	String name;
	@JsonProperty("componentVersion")
	String version;
	@JsonProperty("componentDesc")
	String desc;

}

传入的参数格式是component_id, component_name, component_version, component_desc

**Comment by IamFive** [comment]
稍等。这个要分两个类来处理了。。 4.2.3 查询集群详情 中用的是

```
 { 
                "componentId":"MRS 1.3.0_001", 
                "componentName":"Hadoop", 
                "componentVersion":"2.7.2", 
                "componentDesc":"A framework that allows for the distributed processing of large data sets across clusters." 
            }

```

**Comment by IamFive** [comment]
好了

**Comment by IamFive** [comment]
昨天 MRS的同事有联系你吗？他昨天给我打电话了，我让他直接联系你。

**Comment by swx424265** [comment]
联系了，今天也问了他一些问题

**Comment by IamFive** [comment]
ok 辛苦了，有什么反馈让我知道哈。

**Comment by IamFive** [comment]
更新下代码哈，上次有些地方没改完整。

**Comment by swx424265** [comment]
新拉下来的代码编译失败了

**Comment by IamFive** [comment]
稍等，我本地编译下看看。

**Comment by IamFive** [comment]
我本地没问题诶，方便发下错误信息吗。

**Comment by swx424265** [comment]
unknow lifecycle phase "–DskipTests"

**Comment by IamFive** [comment]
你是不是命令输错了
```
mvn clean package install -DskipTests
```

**Comment by swx424265** [comment]
mvn clean package install -DskipTests

**Comment by IamFive** [comment]
额。。你的环境都没改过吗？试试

```
mvn clean package install  -Dmaven.test.skip=true
```

**Comment by swx424265** [comment]
已经可以了

**Comment by IamFive** [comment]
ok, 是撒问题啊。

**Comment by IamFive** [comment]
另外 MRS 服务端开发有反馈吗。

**Comment by swx424265** [comment]
木有啊

**Comment by IamFive** [comment]
～～～ 问题都提了一个半月了。
