### ISSUE TITLE
[DNS]请提供下SDK与API的对应关系

### ISSUE THREAD

**Issue by dnstester** [Huawei/openstack4j#44]

**Comment by IamFive** [comment]
不是提供过了。


Interface | method | API URL | API description
-- | -- | -- | --
Zone | osclient.dns().zones().create(zone) | POST /v2/zones | Create zone
  | osclient.dns().zones().get("zone-id"); | GET /v2/zones/{zone_id} | Show zone
  | osclient.dns().zones().list() | GET /v2/zones | List zone
  | osclient.dns().zones().delete(zone_id) | DELETE /v2/zones/{zone_id} | Delete zone
  | osclient.dns().zones().listNameservers(zone_id) | GET /v2/zones/{zone_id}/nameservers | List Nameservers
  | osclient.dns().zones().associateRouter(zone_id, router) | POST /v2/zones/{zone_id}/associaterouter | Associate Router
  | osclient.dns().zones().disassociateRouter(zone_id, router) | POST /v2/zones/{zone_id}/disassociaterouter | Disassociate Router
Recordset | osclient.dns().recordsets().create(ZONE_ID, recordset) | POST /v2/zones/{zone_id}/recordsets | Create Recordset
  | osclient.dns().recordsets().get(zone_id, recordset_id) | GET /v2/zone/{zone_id}/recordsets/{recordset_id} | Show a Recordset
  | osclient.dns().recordsets().list() | GET /v2/recordsets | List all Recordsets
  | osclient.dns().recordsets().list(zone_id) | GET /v2/zones/{zone_id}/recordsets | List Recordsets in a Zone
  | osclient.dns().recordsets().delete(zone_id, recordset_id) | DELETE    /v2/zones/{zone_id}/recordsets/{recordset_id} | Delete a Recordset
PTR Record | osclient.dns().ptrs().setup(ptrRecord) | PATCH    /v2/reverse/floatingips/{region}:{floatingip_id} | Set floatingip ptr record
  | osclient.dns().ptrs().restore(region, floatingIpId) | PATCH    /v2/reverse/floatingips/{region}:{floatingip_id} | Unset floatingip ptr record
  | osclient.dns().ptrs().list() | GET /v2/reverse/floatingips | List floatingip ptr records
  | osclient.dns().ptrs().get(region, floatingIpId) | GET /v2/reverse/floatingips/{region}:{floatingip_id} | Show floatingip ptr record details
