### ISSUE TITLE
[SMN]publish消息不成功

### ISSUE THREAD

**Issue by SimpleMessageNotification** [Huawei/openstack4j#46]
topic创建后的，发布模板消息不成功

**Comment by IamFive** [comment]
把 HTTP 请求 发送 跟 返回的内容发上来。

**Comment by IamFive** [comment]
这个问题我们老早就发现了，应该是服务端的问题。要找服务端的同事确认下。

**Comment by IamFive** [comment]
已经邮件给张栋了。

**Comment by SimpleMessageNotification** [comment]
在console端会有一个要求，使用一个命名模板前，会要求有一个同名的默认模板，如果默认模板不存在，会报错

**Comment by IamFive** [comment]
@SimpleMessageNotification  这个我不清楚哦，文档上没有这个的说明。 
你那边看下要怎么创建，能不能在console创建一个呢。

**Comment by SimpleMessageNotification** [comment]
protocol应该 有一个默认的协议default

**Comment by IamFive** [comment]
名称 | 是否必选 | 参数类型 | 说明 | 约束
-- | -- | -- | -- | --
endpoint | 是 | String | 消息的接入点 | http协议，接入点必须以“http://”开头。   https协议，接入点必须以“https://”开头。   email协议，接入点必须是邮件地址。   sms协议，接入点必须是一个电话号码。
protocol | 是 | String | 协议说明endpoint推送的方式 | 目前支持“email”、“sms”、“http”和“https”
remark | 否 | String | 备注 | 126byte约42个中文，必须是UTF-8编码的字符串，否则无法正常显示中文。

**Comment by SimpleMessageNotification** [comment]
协议目前就这4种，未来还会增加。模板的发送除了支持这四种协议之外，还一个默认的同名模板

**Comment by IamFive** [comment]
那我是在 Protocol 那个类里面 加个 default 类型吗？

**Comment by IamFive** [comment]
好像没问题了。你在看下 `MessageSample` 的代码
