### ISSUE TITLE
创建集群并执行作业,请求体多封装了一层,add_jobs应允许空集如"add_jobs": []

### ISSUE THREAD

**Issue by swx424265** [Huawei/openstack4j#49]
期望:
{ 
    "billing_type": 12,  
    "data_center": "eu-de",  
    ...
    "component_list": [ 
        { 
            "component_id": "MRS 1.5.0_001",  
            "component_name": "Hadoop",  
            "component_version": "2.7.2",  
            "component_desc": "" 
        }
    ],  
    "add_jobs": [ 
        { 
            "job_type": 1,  
            "job_name": "tenji111",  
            "jar_path": "s3a://bigdata/program/hadoop-mapreduce-examples-2.7.2.jar",  
            "arguments": "wordcount",  
            "input": "s3a://bigdata/input/wd_1k/",  
            "output": "s3a://bigdata/ouput/",  
            "job_log": "s3a://bigdata/log/",  
            "shutdown_cluster": true,  
            "file_action": "",  
            "submit_job_once_cluster_run": true,  
            "hql": "",  
            "hive_script_path": "" 
        } 
    ] 
}
但是
{"cluster":{ 
    "billing_type": 12,  
    "data_center": "eu-de",  
    ...
    "component_list": [ 
        { 
            "component_id": "MRS 1.5.0_001",  
            "component_name": "Hadoop",  
            "component_version": "2.7.2",  
            "component_desc": "" 
        }
    ],  
    "add_jobs": [ 
        { 
            "job_type": 1,  
            "job_name": "tenji111",  
            "jar_path": "s3a://bigdata/program/hadoop-mapreduce-examples-2.7.2.jar",  
            "arguments": "wordcount",  
            "input": "s3a://bigdata/input/wd_1k/",  
            "output": "s3a://bigdata/ouput/",  
            "job_log": "s3a://bigdata/log/",  
            "shutdown_cluster": true,  
            "file_action": "",  
            "submit_job_once_cluster_run": true,  
            "hql": "",  
            "hive_script_path": "" 
        } 
    ] 
}
}

**Comment by IamFive** [comment]
不允许的啊，文档是是必填项，且只能有一个job

**Comment by swx424265** [comment]
那能改成能传空集吗,还是上面的其他问题改掉

**Comment by IamFive** [comment]
没理解你意思。

**Comment by IamFive** [comment]
好了，更新下代码。

**Comment by IamFive** [comment]
你打的电话吗，接起来没声音

**Comment by swx424265** [comment]
已经没问题了

**Comment by IamFive** [comment]
我德电测试 怎么还是 500 。。

**Comment by swx424265** [comment]
执行的什么

**Comment by IamFive** [comment]
就是 “创建集群并执行作业” 这个API

**Comment by swx424265** [comment]
osClient.sahara().clusters2().createAndRunJob(cluster, null);看看传nul会不会爆500l

**Comment by IamFive** [comment]
会

```
1 > POST https://mrs.eu-de.otc.t-systems.com/v1.1/d4f2557d248e4860829f5fef030b209c/run-job-flow
1 > Accept: application/json
1 > Content-Type: application/json
1 > User-Agent: OpenStack4j / OpenStack Client
{
  "cluster_name" : "newcluster",
  "cluster_version" : "MRS 1.3.0",
  "cluster_type" : 0,
  "master_node_num" : 2,
  "core_node_num" : 3,
  "master_node_size" : "c2.4xlarge.linux.mrs",
  "core_node_size" : "s1.xlarge.linux.mrs",
  "billing_type" : 12,
  "data_center" : "eu-de",
  "available_zone_id" : "eu-de-01",
  "vpc_id" : "31d158b8-e7d7-4b4a-b2a7-a5240296b267",
  "vpc" : "vpc-console-bosh",
  "subnet_id" : "cb9a6ede-39c6-498f-ad85-c554ef7220fc",
  "subnet_name" : "cf2",
  "volume_type" : "SSD",
  "volume_size" : 100,
  "node_public_cert_name" : "KeyPair-28ice",
  "safe_mode" : 0,
  "component_list" : [ {
    "component_id" : "MRS 1.3.0_001",
    "component_name" : "Hadoop",
    "component_version" : "",
    "component_desc" : ""
  } ],
  "add_jobs" : [ ]
}

八月 25, 2017 10:56:00 上午 org.glassfish.jersey.filter.LoggingFilter log
信息: 1 * Client response received on thread main
1 < 500
1 < Connection: keep-alive
1 < Content-Length: 58
1 < Content-Type: application/json
1 < Date: Fri, 25 Aug 2017 02:55:52 GMT
1 < Server: nginx
{"errorCode":"12000004","message":"Internal Server Error"}
```

**Comment by swx424265** [comment]
10.154.48.79 mrs.eu-de.otctest.t-systems.com应该是这个吧

**Comment by swx424265** [comment]
你的公网域名错的把

**Comment by IamFive** [comment]
没错的。。我那个是德电生产环境的。

**Comment by swx424265** [comment]
那就不清楚了,我这边可以创建

**Comment by swx424265** [comment]
DT环境,不是德电环境吗

**Comment by IamFive** [comment]
那我也不清楚了，你那能通过就好吧。
