### ISSUE TITLE
CES的测试文件CloudEyeSample.java的testGetMetrics方法的问题

### ISSUE THREAD

**Issue by 42701618** [Huawei/openstack4j#5]
MetricFilterOptions options =config.dim(null); 这时报错

**Comment by IamFive** [comment]
Fixed， 正常用户不会这么用吧。 :)

**Comment by IamFive** [comment]
![q -20170701084416](https://user-images.githubusercontent.com/1578702/27757825-86f917f6-5e39-11e7-8c5e-1be1a7ed806f.png)

**Comment by 42701618** [comment]
marker 的问题。表格里的参数和我们的不一样

**Comment by IamFive** [comment]
恩，我知道是不一样的。但是正常情况下，就是我截图的那种方式。
Metric这个比较特殊，没有ID。代码里面我已经处理了，加了个getId() 方法，会返回拼接的 ID

**Comment by 42701618** [comment]
还有config.dim(null); ，CloudEyeSample怎么一点异常的信息也没打出来。

**Comment by IamFive** [comment]
config.dim(null), 现在会直接就会忽略掉这个参数。

还是说我要抛出异常呢。

**Comment by 42701618** [comment]
这个正常是要要抛出异常，方便定位问题吧。我当时是debug后才定位出来的。
这里你这么改也可以。

**Comment by IamFive** [comment]
ok, 我觉得现在这样可以，因为使用SDK的都是开发者，他们正常都会保证输入参数的合法性的。不然在开发阶段就会发现问题了。
