### ISSUE TITLE
获取SDK失败

### ISSUE THREAD

**Issue by sl061201124** [Huawei/openstack4j#55]
## 参照 https://huawei.github.io/openstack4j/#/zh-cn/quickstart 中sdk的获取方式，本地运行报错如下
D:\JavaSpace\MyProject\openstack4j>mvn clean package install –DskipTests
......
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building OpenStack4j Parent 3.0.5.1
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] OpenStack4j Parent ................................. FAILURE [  0.037 s]
[INFO] OpenStack4j Core ................................... SKIPPED
[INFO] OpenStack4j Connectors ............................. SKIPPED
[INFO] OpenStack4j HttpComponents-HttpClient Connector .... SKIPPED
[INFO] OpenStack4j Test Cases ............................. SKIPPED
[INFO] OpenStack4j Jersey2 Connector ...................... SKIPPED
[INFO] OpenStack4j RestEasy Connector ..................... SKIPPED
[INFO] OpenStack4j OKHttp Connector ....................... SKIPPED
[INFO] OpenStack4j HttpURL Connector ...................... SKIPPED
[INFO] OpenStack4j Distribution ........................... SKIPPED
[INFO] OpenStack4j Integration test Cases ................. SKIPPED
[INFO] OpenStack4j IntegrationTest Jersey2 Connector ...... SKIPPED
[INFO] OpenStack4j IntegrationTest RestEasy Connector ..... SKIPPED
[INFO] OpenStack4j IntegrationTest OKHttp Connector ....... SKIPPED
[INFO] OpenStack4j IntegrationTest Apache HttpClient ...... SKIPPED
[INFO] openstack4j-sample ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.662 s
[INFO] Finished at: 2017-08-30T10:56:46+08:00
[INFO] Final Memory: 10M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase "–DskipTests". You must specify a valid lifecyc
le phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<pl
ugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: val
idate, initialize, generate-sources, process-sources, generate-resources, proces
s-resources, compile, process-classes, generate-test-sources, process-test-sourc
es, generate-test-resources, process-test-resources, test-compile, process-test-
classes, test, prepare-package, package, pre-integration-test, integration-test,
 post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, p
re-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhase
NotFoundException

D:\JavaSpace\MyProject\openstack4j>

**Comment by IamFive** [comment]
@swx424265 你上次是不是也碰到一样问题，是咋处理的。

**Comment by IamFive** [comment]
你试下自己手动敲这些命令？拷贝的有撒特殊字符没有。

**Comment by sl061201124** [comment]
嗯，确实是拷贝的文件里面的命令里面有特殊字符吧

分割线
---------------------------------------------------------
源码导入有些类提示找不到?

import com.huawei.openstack4j.openstack.trove.domain.Database.DatabaseBuilder;
import com.huawei.openstack4j.openstack.trove.domain.DatabaseInstanceCreate.DatabaseInstanceCreateBuilder;
import com.huawei.openstack4j.openstack.trove.domain.DatabaseUser.DatabaseUserBuilder;
....

**Comment by IamFive** [comment]
你是要在源码上进行开发吗，源码中使用了 lombok 来实现类增强。IDE安装对应的插件就可以了，Eclipse，IDEA等都有相应的插件。
