### ISSUE TITLE
【as】移除伸缩实例接口有问题

### ISSUE THREAD

**Issue by caoyameng** [Huawei/openstack4j#57]
String instanceId = "27804afc-8de6-454a-9265-c5fd42b2e023";
		ActionResponse resp = osclient.autoScaling().groupInstances().delete(instanceId, true);

 无论instanceId 是否存在，结果均为：
ActionResponse{success=false, fault=[AS.0007] The resources requested cannot be found., code=404}

已用POSTMAN验证该接口，没有问题；

**Comment by IamFive** [comment]
能把日志信息贴上来，我看了请求的内容没有问题。

**Comment by caoyameng** [comment]
我看不了现网的后台日志，我试过很多次，都是报的404，这个肯定是有问题

**Comment by caoyameng** [comment]
还有我这边生成不了JAR报，如果修改的话把能不能帮忙生成JAR？

**Comment by IamFive** [comment]
1. 不是要后台日志，要的是客户端的日志。
2. 问题不像是在客户端这边，因为发送的请求数据跟文档提供的一致。
3. 为嘛不能生成jar？源码下载，然后 mvn clean package install -DskipTests 就会在本地生成jar了啊。
