### ISSUE TITLE
CloudEyeSample.java里的testAddMetricsDatas方法问题

### ISSUE THREAD

**Issue by 42701618** [Huawei/openstack4j#8]
上传一个指标，不能有id ,你看看接口的文档
"{"code":400,"element":"Bad Request","message":"The system received a request which cannot be recognized","details":{"details":"Some content in message body is not correct","code":"ces.0014"}}"

**Comment by IamFive** [comment]
上次的那个 marker 问题，后来加了个 getId() 方法引起的估计。。
稍等我让开发改一下。

**Comment by IamFive** [comment]
同时把 异常的信息优化了，服务端返回的异常详情，会体现在异常信息里面或这 ActionResponse里。

**Comment by 42701618** [comment]
好
